### ISSUE TITLE
Slider becomes 100% unusable when wrapped in a flex column container (Firefox Dev Ed v113.0b7)

### ISSUE THREAD

**Issue by televators** [NickPiscitelli/Glider.js#252]
# The Issue
I dug through all 11 pages of issues, tried toggling all my Glider settings, tried restarting my machine even, and finally figured out what's happening.

I've got a simple static landing page I'm working on and am trying Glider for the first time (long time Slick user), and it was all gravy until all of a sudden in the middle of building out the section, the slider just stopped working entirely. Glider would initialize, the slider and navigation would be instantiated, but it was completely uninteractive, i.e., clicking on the prev/next buttons and dots did nothing, dragging didn't work, just sitting there unusable.

After much hair pulling, realized that once I disabled the following CSS, interactivity was restored:
```flex-flow: column nowrap;```
Really not sure why that would be since visually at least everything looks fine. Everything is in the correct place and sized correctly, and Glider does indeed initialize.

# My Setup
Note: I'm working in Firefox Developer Edition (113.0b7), but issue is present in regular Firefox (112) as well as Chrome (112.0.5615.138). I'm on Windows 10 22H2.

## HTML
```html
<div class="gallery__inner">
  <div class="gallery__slider">
    <div class="gallery__slide">
      <img src="assets/img/photos/deer-1.jpg" alt="Drone shot of deer loaded onto MLX basket">
    </div>
    <div class="gallery__slide">
      <img src="assets/img/photos/deer-2.jpg" alt="Up close shot of deer loaded onto MLX basket">
    </div>
    <!-- more slides... -->
  </div>

  <nav class="gallery__nav">
    <button aria-label="Previous" class="glider-prev">«</button>
    <div role="tablist" class="dots"></div>
    <button aria-label="Next" class="glider-next">»</button>
  </nav>
</div>
```
## JS
```js
window.addEventListener( 'load', function() {
  new Glider( document.querySelector( '.gallery__slider' ), {
    slidesToShow: 3,
    arrows: {
      prev: document.querySelector( '.glider-prev' ),
      next: document.querySelector( '.glider-next' ),
    },
    dots: document.querySelector( '.dots' ),
  } );
} );
```

## CSS
```css
.gallery__inner {
  display: flex;
  /* Setting flex-direction to column breaks everything, either with flex-direction directly or in flex-flow. */
  flex-flow: column nowrap;
  align-items: center;
  justify-content: center;
  max-width: calc( 100vw - 6rem );
}
```

If I need to include any other info, please let me know! And thank you for building a nice successor to the legendary Slick that's just as nice to use.
